---
version: '3'
services:
  backend:
    build: maven/
    container_name: maven
    volumes:
      - docker-compose_temp:/opt/boxfuse/target/

  web:
    build: tomcat/
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - docker-compose_temp:/opt/tomcat/webapps/

volumes:
  docker-compose_temp: