---
version: '3'
services:
  web:
    build: tomcat/
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on: backend
    volumes:
      - warfile:/opt/tomcat/webapp

  backend:
    build: maven/
    container_name: maven
    volumes:
      - warfile:/tmp/boxfuse-sample-java-war-hello/target/
volumes:
  warfile: