---
version: '3'
services:

  web:
    build: tomcat/
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - exchange:/opt/tomcat/exchange/
  backend:
    build: maven/
    container_name: maven
    volumes:
      - exchange:/opt/boxfuse/target
volumes:
  exchange: