---
version: '3'
services:
  web:
    build: tomcat/
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - type: volume
        source: backend:/tmp/boxfuse*/target/
        target: /opt/tomcat/webapps/
  backend:
    build: maven/
    container_name: maven